msm: pcie: Replicate prototype change of msm_pcie_destroy_irq()
Downstream commit 4a17397256b6 ("pci: msm: add support for multiple msi
interrupts") made changes to arch_setup_msi_irq_default() which calls
msm_pcie_destroy_irq(). An upstream commit recently changed the
signature of msm_pcie_destroy_irq(), and we need to replicate that
change in arch_setup_msi_irq_default().

Previously, we saw this error message:

/usr/local/ssd2/home/danielmentz/android/kernel/p-dev-msm-bluecross-4.9/private/msm-google/drivers/pci/host/pci-msm.c:4962:25: error: incompatible integer to pointer conversion passing 'int'
      to parameter of type 'struct msi_desc *' [-Werror,-Wint-conversion]
                        msm_pcie_destroy_irq(irq, pdev);
                                             ^~~
/usr/local/ssd2/home/danielmentz/android/kernel/p-dev-msm-bluecross-4.9/private/msm-google/drivers/pci/host/pci-msm.c:4826:51: note: passing argument to parameter 'entry' here
static void msm_pcie_destroy_irq(struct msi_desc *entry, unsigned int irq)
                                                  ^
/usr/local/ssd2/home/danielmentz/android/kernel/p-dev-msm-bluecross-4.9/private/msm-google/drivers/pci/host/pci-msm.c:4962:30: error: incompatible pointer to integer conversion passing
      'struct pci_dev *' to parameter of type 'unsigned int' [-Werror,-Wint-conversion]
                        msm_pcie_destroy_irq(irq, pdev);
                                                  ^~~~
/usr/local/ssd2/home/danielmentz/android/kernel/p-dev-msm-bluecross-4.9/private/msm-google/drivers/pci/host/pci-msm.c:4826:71: note: passing argument to parameter 'irq' here
static void msm_pcie_destroy_irq(struct msi_desc *entry, unsigned int irq)
                                                                      ^
2 errors generated.

Change-Id: I93277965655fb0f7e17bbc7effe432b83835a631
Signed-off-by: Daniel Mentz <danielmentz@google.com>
Signed-off-by: Rapherion Rollerscaperers <rapherion@raphielgang.org>