printk: fix stringop-truncation warning
Since destination size equals number of characters to copy.
Pointed out by gcc8. [-Werror=stringop-truncation]

Fixes this following warning:
In function ‘strncpy’,
    inlined from ‘control_devkmsg’ at ../kernel/printk/printk.c:137:3:
../include/linux/string.h:196:9: error: ‘__builtin_strncpy’ output truncated before terminating nul copying 2 bytes from a string of the same length [-Werror=stringop-truncation]
  return __builtin_strncpy(p, q, size);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘control_devkmsg’ at ../kernel/printk/printk.c:140:3:
../include/linux/string.h:196:9: error: ‘__builtin_strncpy’ output truncated before terminating nul copying 3 bytes from a string of the same length [-Werror=stringop-truncation]
  return __builtin_strncpy(p, q, size);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Raphiel Rollerscaperers <raphielscape@outlook.com>