Revert "DEBUG: Sched: Improve load balancer tracing support"
../include/trace/events/sched.h: In function 'trace_event_raw_event_sched_load_balance_skip_tasks':
../include/trace/events/sched.h:2060:40: error: 'struct rq' has no member named 'cum_window_demand'
 2060 |   __entry->src_util_cum  = cpu_rq(scpu)->cum_window_demand;
      |                                        ^~

Probably going to adapt this to WALT which won't see cum_window_demand anywhere around later maybe

This reverts commit ab8d1ac5731a5a2e8805af7321507159616a66e4.

Signed-off-by: Raphiel Rollerscaperers <rapherion@raphielgang.org>